import sys

import hypothesis.strategies as strats
import pytest
from hypothesis import given

from dumbpw.candidate import Candidate, Char, Void
from dumbpw.errors import DumbConstraintError


def random_chars(**kwargs):
    """
    Returns a list of Char objects, one for each character
    generated by st.text().
    """
    return strats.text(**kwargs).map(
        lambda s: [Char(c) if len(c) else Void() for c in s]
    )


def test_candidate_zero_len_duplicates():
    cd = Candidate("")

    assert not cd.has_duplicates


@given(random_chars(min_size=1))
def test_candidate_has_duplicates(text):
    cd = Candidate(text + text)

    assert cd.has_duplicates


@given(random_chars(min_size=1))
def test_candidate_has_no_duplicates(text):
    cd = Candidate(list(set(text)))

    assert not cd.has_duplicates


def test_candidate_zero_len_repeating():
    cd = Candidate([])

    assert not cd.has_repeating


@given(random_chars(min_size=1, max_size=1))
def test_candidate_has_repeating(text):
    cd = Candidate([text, text])

    assert cd.has_repeating


@given(random_chars(min_size=1))
def test_candidate_has_no_repeating(text):
    cd = Candidate(list(set(text)))

    assert not cd.has_repeating


@given(random_chars())
def test_candidate_copy_method(text):
    cd = Candidate(text)
    cp = cd.copy()

    assert cd == cp
    assert cd is not cp


@given(random_chars())
def test_candidate_addable(text):
    """Candidate can be added together."""
    cd = Candidate(text)

    cd += Candidate([Char("a")])

    assert str(cd) == "".join(str(c) for c in text) + "a"


@given(random_chars())
def test_candidate_stringifiable(text):
    """Candidate can be coerced to a string."""
    cd = Candidate(text)

    assert str(cd) == "".join(str(c) for c in text)


@given(random_chars(min_size=1))
def test_candidate_subscriptable(text):
    """Candidate is subscriptable."""
    cd = Candidate(text)

    assert cd[0] == text[0]


@given(random_chars())
def test_candidate_hashable(text):
    """Candidate is hashable."""
    c1 = Candidate(text)
    c2 = Candidate(text)

    assert hash(c1) == hash(c2)


@given(random_chars())
def test_candidate_sizable(text):
    """Candidate is sizable."""
    cd = Candidate(text)

    assert sys.getsizeof(cd) is not None
    assert sys.getsizeof(cd) > 0


def test_candidate_strict_equality_logic(mocker):
    """Equality agrees with hash."""
    c1 = Candidate("abc")
    c2 = Candidate(["a", "b", "c"])
    c3 = Candidate("abd")

    assert c1 == c2
    assert c1 != c3
    assert c1 != "abc"
    assert hash(c1) == hash(c2)
    assert len({c1, c2}) == 1
    assert len({c1, c3}) == 2


def test_candidate_scatter_firstlast(mocker):
    """Scattering does not compare the first and last as duplicates."""
    mock_choice = mocker.patch("secrets.choice")
    mock_random = mocker.patch("secrets.SystemRandom")
    mock_random.return_value.shuffle.side_effect = lambda x: x.sort()
    mock_choice.return_value = 0

    cd = Candidate(" XYA")
    cd.scatter(count=1, charstack=["A"], allow_repeating=False)

    assert str(cd._text[0]) == "A"


def test_candidate_scatter_unsatisfiable(mocker):
    """Scatter raises DumbConstraintsError."""
    mock_choice = mocker.patch("secrets.choice")
    mock_random = mocker.patch("secrets.SystemRandom")
    mock_random.return_value.shuffle.side_effect = lambda x: x.sort()
    mock_choice.return_value = 3

    cd = Candidate("    ")
    cd.scatter(count=1, charstack=["A"], allow_repeating=False)

    cd = Candidate("AAA ")
    with pytest.raises(DumbConstraintError):
        cd.scatter(count=1, charstack=["A"], allow_repeating=False)
