---
name: CI

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - dumbpw/**
      - tests/**
      - pyproject.toml
      - uv.lock
      - .pre-commit-config.yaml
      - .github/workflows/integration.yaml

jobs:
  lint:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.14"]
    runs-on: ubuntu-latest
    steps:
      # ----------------------------------------------
      # check-out repo and set-up python
      # ----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      # ----------------------------------------------
      # build virtual environment and install
      # ----------------------------------------------
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
        with:
          github-token: ${{ github.token }}
      - name: Run pre-commit checks
        run: uv tool run pre-commit run --all-files --show-diff-on-failure

  test:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: ${{ matrix.os }}
    steps:
      # ----------------------------------------------
      # check-out repo and set-up python
      # ----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      # ----------------------------------------------
      # build virtual environment and install
      # ----------------------------------------------
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
        with:
          github-token: ${{ github.token }}

      # ----------------------------------------------
      # run tests
      # ----------------------------------------------
      - name: Run tests
        run: uv run pytest
