---
name: CI

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - dumbpw/**
      - tests/**
      - pyproject.toml
      - uv.lock
      - .pre-commit-config.yaml
      - .github/workflows/integration.yaml

jobs:
  lint:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.14"]
    runs-on: ubuntu-latest
    steps:
      # ----------------------------------------------
      # check-out repo and set-up python
      # ----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6.1.0
      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}

      # ----------------------------------------------
      # build virtual environment and install
      # ----------------------------------------------
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          github-token: ${{ github.token }}
      - name: Run pre-commit checks
        run: uv tool run pre-commit run --all-files --show-diff-on-failure

  test:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: ${{ matrix.os }}
    steps:
      # ----------------------------------------------
      # check-out repo and set-up python
      # ----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6.1.0
      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}

      # ----------------------------------------------
      # build virtual environment and install
      # ----------------------------------------------
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
        with:
          github-token: ${{ github.token }}

      # ----------------------------------------------
      # run tests
      # ----------------------------------------------
      - name: Run tests
        run: uv run pytest
